image: c11k/serviceandgoods:latest

stages:
  - build
  - test
  - stage

refresh_cache:
  stage: build
  cache:
    key: "$CI_PROJECT_PATH_SLUG-$CI_COMMIT_BRANCH"
    paths:
      - .yarn
      - node_modules
      - public
      - vendor
  script:
    - curl -sL https://deb.nodesource.com/setup_14.x | bash -
    - apt-get install -y nodejs
    - npm install -g yarn
    - composer install --no-plugins --no-scripts
    - yarn config set cache-folder .yarn
    - yarn install --pure-lockfile
    - npm run prod

test:
  stage: test
  image: c11k/serviceandgoods:pcov
  script:
    - cp .env.testing .env
    - touch database/database.sqlite
    - composer install --no-plugins --no-scripts
    - php artisan key:generate
    - composer pretest
    - composer test
  cache:
    key: "$CI_PROJECT_PATH_SLUG-$CI_COMMIT_BRANCH"
    policy: pull
    paths:
      - .yarn
      - vendor
  artifacts:
    paths:
    - tests/coverage
  except:
    - ci
  interruptible: true

dusktest:
  variables:
    MYSQL_ROOT_PASSWORD: 'rootpw'
    MYSQL_DATABASE: 'serviceandgoods'
    MYSQL_USER: 'serviceandgoods'
    MYSQL_PASSWORD: 'serviceandgoods'
  services:
    - mysql:8.0
  allow_failure: true
  image: edbizarro/gitlab-ci-pipeline-php:7.4-chromium
  stage: test
  script:
    - yarn config set cache-folder .yarn
    - yarn install --pure-lockfile
    - yarn run prod
    - composer install --no-plugins --no-scripts --no-progress --no-suggest --prefer-dist --optimize-autoloader
    - php artisan dusk:chrome-driver
    - cp .env.dusk.ci .env
    - php artisan key:generate
    - php artisan migrate:refresh
    - php artisan db:seed --class UsersTableSeeder
    - php artisan serve > /dev/null 2>&1 &
    - ./vendor/laravel/dusk/bin/chromedriver-linux --verbose --port=9515 --whitelisted-ips= &
    - echo "Waiting for chrome to settle..."
    - sleep 5
    - php artisan dusk
  cache:
    key: "$CI_PROJECT_PATH_SLUG-$CI_COMMIT_BRANCH"
    policy: pull
    paths:
      - .yarn
      - node_modules
      - public
      - vendor
  except:
    - ci
  interruptible: true
  artifacts:
    paths:
      - ./storage/logs  # for debugging
      - ./tests/Browser/screenshots # for Dusk screenshots
      - ./tests/Browser/console
    expire_in: 7 days
    when: always

deploy_staging:
  stage: stage
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - composer global require "laravel/envoy=~1.0"
    - ~/.composer/vendor/bin/envoy run deploy --web_hook=$LOG_SLACK_WEBHOOK_URL --release_url=$CI_ENVIRONMENT_URL
  environment:
    name: staging
    url: https://inventory.jeffharris.us
  only:
    - tags

pages:
  stage: stage
  dependencies:
    - test
  script:
    - rm -rf public
    - mv tests/coverage public
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
    - development
