###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
# For development
version: "2.4"
services:

  mailhog:
    image: mailhog/mailhog:latest
    container_name: c11k-mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"

  redis:
    image: redis:alpine
    container_name: c11k-redis
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: c11k-mysql
    restart: unless-stopped
    working_dir: /application
    volumes:
      - .:/application:delegated
      - ./mysql-data:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=c11k
      - MYSQL_USER=c11k
      - MYSQL_PASSWORD=c11k
    ports:
      - "13306:3306"
    healthcheck:
      test: mysqladmin -h 127.0.0.1 -u root -prootpw --silent ping
      interval: 5s
      retries: 8

  selenium:
    image: selenium/standalone-chrome
    container_name: c11k-selenium
    ports:
      - 4444:4444

  webserver:
    image: nginx:alpine
    container_name: c11k-webserver
    restart: unless-stopped
    working_dir: /application
    volumes:
      - .:/application:delegated
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  php-fpm:
    build: phpdocker/php-fpm
    container_name: c11k-php-fpm
    restart: unless-stopped
    working_dir: /application
    volumes:
      - .:/application:delegated
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
