###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
# For development
version: "2.4"

networks:
  web:
    external: true
  internal:
    external: false

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: inventory-mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
    labels:
      - traefik.enable=false
    networks:
      - internal

  redis:
    image: redis:alpine
    container_name: inventory-redis
    restart: unless-stopped
    labels:
      - traefik.enable=false
    networks:
      - internal

  mysql:
    image: mysql:8.0
    container_name: inventory-mysql
    restart: unless-stopped
    working_dir: /application
    volumes:
      - .:/application:delegated
      - ./mysql-data:/var/lib/mysql:delegated
      - ./phpdocker/mysql/default-authentication-plugin:/etc/mysql/mysql.conf.d/default-authentication-plugin.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=serviceandgoods
      - MYSQL_USER=serviceandgoods
      - MYSQL_PASSWORD=serviceandgoods
    healthcheck:
      test: mysqladmin -h 127.0.0.1 -u root -prootpw --silent ping
      interval: 5s
      retries: 8
    labels:
      - traefik.enable=false
    networks:
      - internal
    ports:
      - 13306:3306

  webserver:
    image: nginx:alpine
    container_name: inventory-webserver
    restart: always
    working_dir: /application
    volumes:
      - .:/application:delegated
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - internal
      - web
    labels:
      - traefik.backend=inventory
      - traefik.frontend.rule=Host:inventory.jeffharris.us
      - traefik.docker.network=web
      - traefik.port=80
      - traefik.enable=true
      - "traefik.http.routers.inventory-secure.entrypoints=https"
      - "traefik.http.routers.inventory-secure.rule=Host(`inventory.jeffharris.us`)"
      - "traefik.http.routers.inventory-secure.middlewares=httpd-security"
      - "traefik.http.routers.inventory-secure.tls.certresolver=myhttpchallenge"
      - "traefik.http.middlewares.httpd-security.headers.frameDeny=true"
      - "traefik.http.middlewares.httpd-security.headers.SSLHost=inventory.jeffharris.us"
      - "traefik.http.middlewares.httpd-security.headers.SSLRedirect=true"
    ports:
      - 8080:80

  php-fpm:
    image: c11k/serviceandgoods
    container_name: inventory-php-fpm
    restart: always
    working_dir: /application
    volumes:
      - .:/application:delegated
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    labels:
      - traefik.enable=false
    networks:
      - internal
